### ISSUE TITLE
Context Root Not Found while accessing P2P & PubSub from macOS browser.

### ISSUE THREAD

**Issue by swarnaditya** [WASdev/sample.jms11#2]
Liberty server is accessible. JMSSample app is running 
verified logs msseage.log

IDE: Eclipse, IntelliJ
OS: macOS

**Comment by scriptkiddie123** [comment]
Hello.
As far as I can tell this sample can't run with out a few modifications.
1: The maven-liberty-plugin is version 1.1-SNAPSHOT, which is no longer available, so change it to version 1.1
2: The pom.xml is only installing some of the features, so you need to add '<feature>servlet-3.0</feature>' on line 100.

Last but not least the maven-liberty-plugin is only activated with the wlp profile, so you have to run the following
`mvn install -Pwlp`
And it should work.

**Comment by scottkurz** [comment]
Thx @scriptkiddie123.  I added some updates and comments to the PR #3 in my fork as well.

**Comment by scottkurz** [comment]
OK merged #3 and also #4 to hopefully make things clearer.   You can just run `mvn liberty:dev` now and it should work.

**Comment by scottkurz** [comment]
Feel free to reopen or reach us at https://gitter.im/OpenLiberty/developer-experience if you have more questions
